language: r
install:
- R -e "0" --args --bootstrap-packrat
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/packrat/src"
  - "$TRAVIS_BUILD_DIR/packrat/lib"
  packages: true
script:
- nohup R --slave --no-restore -e 'shiny::runApp(port = 3000)' &
- R -f test.R
addons:
  sauce_connect:
    username: "$SAUCE_USERNAME"
    access_key: "$SAUCE_SECRET_KEY"